const MOBILE_BREAKPOINT = 575;
const MEDIUM_BREAKPOINT = 900;
const LARGE_BREAKPOINT = 1170;
const WIDE_BREAKPOINT = 1440;
const ULTRA_WIDE_BREAKPOINT = 1920;

export const breakpoints = {
  sm: MOBILE_BREAKPOINT,
  md: MEDIUM_BREAKPOINT,
  lg: LARGE_BREAKPOINT,
  xl: WIDE_BREAKPOINT,
  xxl: ULTRA_WIDE_BREAKPOINT,
};
